using GestionLibros.Data;
var path = Path.Combine(Path.GetTempPath(), $"fredi-tests-{Guid.NewGuid():N}.db3");
var db = new AppDatabase(path);
void Check(bool condition, string description) { if (!condition) throw new Exception(description); Console.WriteLine("PASS " + description); }
async Task Denied(Func<Task> action, string description) { try { await action(); } catch (InvalidOperationException) { Console.WriteLine("PASS " + description); return; } throw new Exception("Expected denial: " + description); }
Check(await db.NeedsSetup(), "Empty database needs setup");
await db.Setup("master", "Test-only-secret-123");
await Denied(() => db.Setup("master2", "Test-only-secret-123"), "Cannot repeat master setup");
await Denied(() => db.Login("master", "wrong"), "Wrong password rejected");
await db.Login(" MASTER ", "Test-only-secret-123");
await db.AddCompany("Empresa A"); await db.AddCompany("Empresa B");
var companies = await db.Companies(); var a = companies[0].Id; var b = companies[1].Id;
await db.AddUser("operador", "Operator-secret-123", a);
await db.AddAccount(a, "1", "Activos A", ""); await db.AddAccount(b, "1", "Activos B", "");
await db.AddAccount(a, "1.1", "Caja A", "1");
await Denied(() => db.AddAccount(a, "1", "Duplicado", ""), "Duplicate account rejected");
await Denied(() => db.AddAccount(a, "2", "Orphan", "99"), "Missing parent rejected");
Check((await db.Accounts(a)).Single(x => x.Code == "1.1").Level == 2, "Account hierarchy persisted");
db.Logout();
await Denied(async () => { await db.Accounts(a); }, "Logged-out query rejected");
await db.Login("operador", "Operator-secret-123");
Check((await db.Companies()).Count == 1, "Operator sees only assigned company");
Check((await db.Accounts(a)).Count == 2, "Operator reads assigned accounts");
await Denied(async () => { await db.Accounts(b); }, "Cross-company read rejected");
await Denied(() => db.AddAccount(b, "9", "Attack", ""), "Cross-company write rejected");
await Denied(() => db.AddCompany("Unauthorized"), "Operator cannot create companies");
await Denied(() => db.AddUser("other", "Other-secret-123", a), "Operator cannot create users");
await Denied(async () => { await db.Users(); }, "Operator cannot list users");
var reopened = new AppDatabase(path);
Check(!await reopened.NeedsSetup(), "Setup persists across connection reopen");
await reopened.Login("operador", "Operator-secret-123");
Check((await reopened.Accounts(a)).Count == 2, "Accounts persist across connection reopen");
Console.WriteLine("All checks passed. Synthetic database: " + path);

await db.Login("master", "Test-only-secret-123");
await db.AddAccount(a, "2", "Capital", "");
var aAccounts = await db.Accounts(a);
var cash = aAccounts.Single(x => x.Code == "1.1").Id;
var capital = aAccounts.Single(x => x.Code == "2").Id;
var foreign = (await db.Accounts(b)).Single().Id;
GestionLibros.Models.Journal Draft(string reference, DateTime date) => new() { Date = date, Reference = reference, Type = "01", Concept = "Prueba" };
List<GestionLibros.Models.JournalLine> Movement(long cents) => [new() { AccountId = cash, DebitCents = cents }, new() { AccountId = capital, CreditCents = cents }];
await db.SaveJournal(a, Draft("opening", new DateTime(2026, 8, 1)), Movement(10001));
await db.SaveJournal(a, Draft("current", new DateTime(2026, 9, 1)), Movement(2034));
await Denied(() => db.SaveJournal(a, Draft("current", new DateTime(2026, 9, 2)), Movement(10)), "Duplicate journal rejected");
var unbalanced = Movement(100); unbalanced[1].CreditCents = 99;
await Denied(() => db.SaveJournal(a, Draft("bad", new DateTime(2026, 9, 1)), unbalanced), "Unbalanced journal rejected");
var crossCompany = Movement(100); crossCompany[0].AccountId = foreign;
await Denied(() => db.SaveJournal(a, Draft("bad", new DateTime(2026, 9, 1)), crossCompany), "Foreign account rejected");
Check((await db.Journals(a, 2026, 9)).Count == 1, "Invalid journals do not leave headers");
var balance = (await db.Balances(a, 2026, 9)).Single(x => x.Code == "1.1");
Check(balance.Opening == 10001 && balance.Debits == 2034 && balance.Closing == 12035, "Exact cent opening and month balances");
Check((await db.Balances(a, 2026, 9)).Single(x => x.Code == "1").Closing == 12035, "Parent rollup does not duplicate movements");
Check((await db.Balances(b, 2026, 9)).All(x => x.Closing == 0), "Other company balance unchanged");
await Denied(() => db.DeleteAccount(a, cash), "Cannot delete posted account");
await Denied(() => db.AddAccount(a, "1.1.1", "Child", "1.1"), "Cannot add child to posted account");
var saved = (await db.Journals(a, 2026, 9)).Single();
await db.SaveJournal(a, saved, Movement(3045));
Check((await db.Lines(a, saved.Id)).Count == 2, "Edit replaces lines atomically");
Check((await db.Balances(a, 2026, 9)).Single(x => x.Code == "1.1").Closing == 13046, "Edited journal updates balances");
await db.Login("operador", "Operator-secret-123");
await Denied(async () => { await db.Journals(b, 2026, 9); }, "Foreign journal list blocked");
await Denied(async () => { await db.Lines(b, saved.Id); }, "Foreign journal detail blocked");
await Denied(() => db.DeleteJournal(b, saved.Id), "Foreign journal delete blocked");
await db.DeleteJournal(a, saved.Id);
Check((await db.Journals(a, 2026, 9)).Count == 0, "Journal deleted");
Check((await db.Balances(a, 2026, 9)).Single(x => x.Code == "1.1").Closing == 10001, "Delete removes journal effects");
Console.WriteLine("Accounting flow checks passed.");
await db.Login("master", "Test-only-secret-123");
await db.AddAccount(b, "2", "Capital B", "");
var capitalB = (await db.Accounts(b)).Single(x => x.Code == "2").Id;
await db.SaveJournal(b, Draft("B-1", new DateTime(2026, 9, 1)), [new() { AccountId = foreign, DebitCents = 100 }, new() { AccountId = capitalB, CreditCents = 100 }]);
var foreignJournal = (await db.Journals(b, 2026, 9)).Single();
await db.Login("operador", "Operator-secret-123");
await Denied(async () => { await db.Lines(a, foreignJournal.Id); }, "Forged company with foreign journal ID rejected for read");
await Denied(() => db.SaveJournal(a, foreignJournal, Movement(100)), "Forged company with foreign journal ID rejected for edit");
await Denied(() => db.DeleteJournal(a, foreignJournal.Id), "Forged company with foreign journal ID rejected for delete");
await db.SaveJournal(a, Draft("rollback", new DateTime(2026, 9, 1)), Movement(200));
var unchanged = (await db.Journals(a, 2026, 9)).Single();
await Denied(() => db.SaveJournal(a, unchanged, crossCompany), "Invalid edit rejected before replacing lines");
Check((await db.Lines(a, unchanged.Id)).Single(l => l.DebitCents > 0).DebitCents == 200, "Invalid edit preserves saved movements");
Console.WriteLine("All 37 checks passed.");

await ReportingChecks.Run();
